package com.example.demo.Course;

public record Course(long courseCode,String courseName,int credits,String instructor) {
    // Canonical constructor
    public Course {
        System.out.println(String.format("called the canonical constructor of %s, and it is automatically generated by the compiler", courseName));
    }

}